server:
  port: ${SERVER_PORT:8032}
spring:
  main:
    banner-mode: off
  devtools:
    livereload:
      enabled: true
  jpa:
    hibernate:
#      ddl-auto: update
      ddl-auto: validate
    database: mysql
    open-in-view: true
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
  security:
    jwt:
      cookie:
        secure: true          # ← 개발환경: HTTP 허용
        http-only: true
        same-site: lax
        path: /
  app:
    display: https://image.newstomato.com/newstomato/club
    upload:
      root: /test
      ftp:
        host: 1.201.174.63
        port: 21
        user: tomatochain
        password: tomatochain1!

  datasource:
    url: ${DB_URL:jdbc:log4jdbc:mariadb://192.168.10.12:3306/narasarang}
#    url: ${DB_URL:jdbc:log4jdbc:mariadb://1.201.174.218:3306/narasarang}
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    username: ${DB_ID:root}
    password: ${DB_PW:tomato0425@!}
    # 또는 로그4jdbc 래퍼를 계속 쓰려면 아래 두 줄 중복 주석 해제
    hikari:
      connection-timeout: 30000    # 기본 30000
      maximum-pool-size: 10        # 기본 10
      minimum-idle: 1              # 기본 maximum-pool-size
      connection-test-query: SELECT 1
      idle-timeout: 600000         # 기본 600000
      pool-name: ${spring.application.name}-pool

x:
  redirect-url: "https://club1.newstomato.com/twitter/callback"

ttr:
  base-url: http://127.0.0.1:9000
  header-token: 1AA75CC269F33FB15479233CAC6705D2DD0016072F561E1547E4BF731C49C6FD
  wallet-address: TTCJNqEHb9BU5qgQCeHvvqPbQzF6pPmn7UAX
  get-balance: /api/v1/address_balance
  transfer_points: /api/v1/wallet_transfer_to_address

nice:
  call-back: https://club1.newstomato.com/api/auth/pass/callback

original:
  replication: true
